version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: org.infinispan:*
        versions:
          - ">= 12"      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
