name: GitHub CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          cache: 'maven'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean install -B -V -e
